### ISSUE TITLE
reqiurements.txt breaks docker-rm

### ISSUE THREAD

**Issue by joschkappel** [IBM/osslm-docker-adaptor#6]
Current settings in requirements.txt install a set of python libraries that render the docker-rm unusable. 
When used with ALM >= GA 1.2  no containers can be created. Install of container resources results in "Failure from Virtual Infrastructure: 'NoneType' object has no attribute 'read'" failure.

This combination is known to work:
connexion==1.3
gevent==1.2.2
docker==2.7.0
kafka-python==1.3.5
pytz==2017.3
tinydb==3.7.0

**Comment by joschkappel** [comment]
Module loaded with current requirements.txt:
[pip3list_failure.txt](https://github.com/IBM/osslm-docker-adaptor/files/1733571/pip3list_failure.txt)

Modules loaded for no-failure docker-rm:
[pip3list_working.txt](https://github.com/IBM/osslm-docker-adaptor/files/1733572/pip3list_working.txt)

**Comment by jjhardwicke** [comment]
tested with suggested combination and committed.
